export interface EmojiData {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
}

export const emojiData: EmojiData[] = [
  // Fitness & Health
  {
    emoji: "💪",
    name: "flexed biceps",
    category: "fitness",
    keywords: ["muscle", "strength", "workout", "exercise", "gym"],
  },
  {
    emoji: "🏃‍♂️",
    name: "man running",
    category: "fitness",
    keywords: ["run", "jog", "cardio", "exercise", "marathon"],
  },
  {
    emoji: "🏃‍♀️",
    name: "woman running",
    category: "fitness",
    keywords: ["run", "jog", "cardio", "exercise", "marathon"],
  },
  {
    emoji: "🚴‍♂️",
    name: "man biking",
    category: "fitness",
    keywords: ["bike", "cycle", "exercise", "cardio", "sport"],
  },
  {
    emoji: "🚴‍♀️",
    name: "woman biking",
    category: "fitness",
    keywords: ["bike", "cycle", "exercise", "cardio", "sport"],
  },
  {
    emoji: "🧘‍♂️",
    name: "man in lotus position",
    category: "wellness",
    keywords: ["meditation", "yoga", "zen", "mindfulness", "calm"],
  },
  {
    emoji: "🧘‍♀️",
    name: "woman in lotus position",
    category: "wellness",
    keywords: ["meditation", "yoga", "zen", "mindfulness", "calm"],
  },
  {
    emoji: "🏋️‍♂️",
    name: "man lifting weights",
    category: "fitness",
    keywords: ["weight", "strength", "gym", "exercise", "muscle"],
  },
  {
    emoji: "🏋️‍♀️",
    name: "woman lifting weights",
    category: "fitness",
    keywords: ["weight", "strength", "gym", "exercise", "muscle"],
  },
  {
    emoji: "🏊‍♂️",
    name: "man swimming",
    category: "fitness",
    keywords: ["swim", "pool", "water", "exercise", "cardio"],
  },
  {
    emoji: "🏊‍♀️",
    name: "woman swimming",
    category: "fitness",
    keywords: ["swim", "pool", "water", "exercise", "cardio"],
  },
  {
    emoji: "💧",
    name: "droplet",
    category: "health",
    keywords: ["water", "drink", "hydration", "liquid", "wellness"],
  },
  {
    emoji: "🥗",
    name: "green salad",
    category: "health",
    keywords: ["healthy", "vegetables", "diet", "nutrition", "fresh"],
  },
  {
    emoji: "💊",
    name: "pill",
    category: "health",
    keywords: ["medicine", "medication", "health", "treatment", "vitamin"],
  },
  {
    emoji: "🩺",
    name: "stethoscope",
    category: "health",
    keywords: ["medical", "doctor", "health", "checkup", "care"],
  },
  {
    emoji: "😴",
    name: "sleeping face",
    category: "health",
    keywords: ["sleep", "rest", "tired", "nap", "zzz"],
  },
  {
    emoji: "⏰",
    name: "alarm clock",
    category: "health",
    keywords: ["wake", "morning", "sleep", "schedule", "time"],
  },

  // Food & Drink
  {
    emoji: "🍕",
    name: "pizza",
    category: "food",
    keywords: ["eat", "slice", "italian", "cheese", "dinner"],
  },
  {
    emoji: "🍔",
    name: "hamburger",
    category: "food",
    keywords: ["burger", "fast food", "eat", "meal", "lunch"],
  },
  {
    emoji: "🍎",
    name: "red apple",
    category: "food",
    keywords: ["fruit", "healthy", "snack", "nutrition", "diet"],
  },
  {
    emoji: "🍌",
    name: "banana",
    category: "food",
    keywords: ["fruit", "healthy", "potassium", "snack", "yellow"],
  },
  {
    emoji: "🥑",
    name: "avocado",
    category: "food",
    keywords: ["healthy", "green", "fruit", "nutrition", "fat"],
  },
  {
    emoji: "🍓",
    name: "strawberry",
    category: "food",
    keywords: ["fruit", "berry", "sweet", "red", "healthy"],
  },
  {
    emoji: "🥕",
    name: "carrot",
    category: "food",
    keywords: ["vegetable", "orange", "healthy", "vitamin"],
  },
  {
    emoji: "🥦",
    name: "broccoli",
    category: "food",
    keywords: ["vegetable", "green", "healthy", "nutrition", "vitamin"],
  },
  {
    emoji: "☕",
    name: "hot beverage",
    category: "food",
    keywords: ["coffee", "drink", "morning", "caffeine", "hot"],
  },
  {
    emoji: "🍵",
    name: "teacup without handle",
    category: "food",
    keywords: ["tea", "drink", "hot", "green", "relaxing"],
  },
  {
    emoji: "🥛",
    name: "glass of milk",
    category: "food",
    keywords: ["milk", "drink", "calcium", "white", "healthy"],
  },
  {
    emoji: "🍷",
    name: "wine glass",
    category: "food",
    keywords: ["wine", "drink", "alcohol", "red", "relax"],
  },
  {
    emoji: "🍳",
    name: "cooking",
    category: "food",
    keywords: ["egg", "frying", "pan", "breakfast", "cook"],
  },
  {
    emoji: "🧑‍🍳",
    name: "cook",
    category: "food",
    keywords: ["chef", "cooking", "kitchen", "food", "prepare"],
  },

  // Education & Learning
  {
    emoji: "📚",
    name: "books",
    category: "education",
    keywords: ["read", "study", "learn", "knowledge", "school"],
  },
  {
    emoji: "📖",
    name: "open book",
    category: "education",
    keywords: ["read", "study", "learn", "page", "text"],
  },
  {
    emoji: "✏️",
    name: "pencil",
    category: "education",
    keywords: ["write", "draw", "notes", "school", "create"],
  },
  {
    emoji: "🖊️",
    name: "pen",
    category: "education",
    keywords: ["write", "notes", "ink", "document", "sign"],
  },
  {
    emoji: "📝",
    name: "memo",
    category: "education",
    keywords: ["notes", "write", "paper", "list", "document"],
  },
  {
    emoji: "🎓",
    name: "graduation cap",
    category: "education",
    keywords: ["graduate", "education", "degree", "achievement", "school"],
  },
  {
    emoji: "🏫",
    name: "school",
    category: "education",
    keywords: ["education", "learn", "building", "class", "study"],
  },
  {
    emoji: "🧮",
    name: "abacus",
    category: "education",
    keywords: ["math", "calculate", "numbers", "counting", "ancient"],
  },
  {
    emoji: "🔬",
    name: "microscope",
    category: "education",
    keywords: ["science", "research", "lab", "biology", "study"],
  },
  {
    emoji: "⚗️",
    name: "alembic",
    category: "education",
    keywords: ["chemistry", "science", "lab", "experiment", "research"],
  },
  {
    emoji: "🌍",
    name: "earth globe",
    category: "education",
    keywords: ["world", "geography", "planet", "global", "learn"],
  },
  {
    emoji: "💻",
    name: "laptop",
    category: "education",
    keywords: ["computer", "code", "work", "study", "technology"],
  },
  {
    emoji: "🤓",
    name: "nerd face",
    category: "education",
    keywords: ["smart", "glasses", "study", "intelligent", "geek"],
  },
  {
    emoji: "🧠",
    name: "brain",
    category: "education",
    keywords: ["mind", "think", "intelligence", "smart", "memory"],
  },

  // Work & Productivity
  {
    emoji: "💼",
    name: "briefcase",
    category: "work",
    keywords: ["business", "job", "office", "professional", "career"],
  },
  {
    emoji: "🏢",
    name: "office building",
    category: "work",
    keywords: ["business", "work", "corporate", "building", "job"],
  },
  {
    emoji: "📊",
    name: "bar chart",
    category: "work",
    keywords: ["data", "analytics", "business", "graph", "statistics"],
  },
  {
    emoji: "📈",
    name: "chart increasing",
    category: "work",
    keywords: ["growth", "success", "profit", "improvement", "up"],
  },
  {
    emoji: "📉",
    name: "chart decreasing",
    category: "work",
    keywords: ["decline", "loss", "down", "reduction", "decrease"],
  },
  {
    emoji: "💰",
    name: "money bag",
    category: "work",
    keywords: ["money", "wealth", "finance", "rich", "dollar"],
  },
  {
    emoji: "💳",
    name: "credit card",
    category: "work",
    keywords: ["payment", "money", "finance", "purchase", "banking"],
  },
  {
    emoji: "🎯",
    name: "direct hit",
    category: "work",
    keywords: ["target", "goal", "aim", "focus", "objective"],
  },
  {
    emoji: "✅",
    name: "check mark button",
    category: "work",
    keywords: ["done", "complete", "finished", "success", "yes"],
  },
  {
    emoji: "📅",
    name: "calendar",
    category: "work",
    keywords: ["date", "schedule", "plan", "time", "organize"],
  },
  {
    emoji: "⏱️",
    name: "stopwatch",
    category: "work",
    keywords: ["time", "timer", "fast", "speed", "measure"],
  },
  {
    emoji: "📞",
    name: "telephone receiver",
    category: "work",
    keywords: ["call", "phone", "communication", "talk", "contact"],
  },
  {
    emoji: "📧",
    name: "e-mail",
    category: "work",
    keywords: ["email", "message", "communication", "send", "inbox"],
  },
  {
    emoji: "👔",
    name: "necktie",
    category: "work",
    keywords: ["formal", "business", "professional", "suit", "dress"],
  },

  // Entertainment & Hobbies
  {
    emoji: "🎮",
    name: "video game",
    category: "entertainment",
    keywords: ["gaming", "play", "controller", "fun", "digital"],
  },
  {
    emoji: "🎲",
    name: "game die",
    category: "entertainment",
    keywords: ["dice", "game", "chance", "board", "random"],
  },
  {
    emoji: "🃏",
    name: "joker",
    category: "entertainment",
    keywords: ["card", "game", "play", "deck", "wild"],
  },
  {
    emoji: "🎨",
    name: "artist palette",
    category: "entertainment",
    keywords: ["art", "paint", "creative", "color", "brush"],
  },
  {
    emoji: "🖌️",
    name: "paintbrush",
    category: "entertainment",
    keywords: ["art", "paint", "create", "brush", "creative"],
  },
  {
    emoji: "📷",
    name: "camera",
    category: "entertainment",
    keywords: ["photo", "picture", "capture", "memory", "shoot"],
  },
  {
    emoji: "🎵",
    name: "musical note",
    category: "entertainment",
    keywords: ["music", "song", "melody", "sound", "note"],
  },
  {
    emoji: "🎸",
    name: "guitar",
    category: "entertainment",
    keywords: ["music", "instrument", "play", "song", "rock"],
  },
  {
    emoji: "🎹",
    name: "musical keyboard",
    category: "entertainment",
    keywords: ["piano", "music", "instrument", "keys", "play"],
  },
  {
    emoji: "🎬",
    name: "clapper board",
    category: "entertainment",
    keywords: ["movie", "film", "cinema", "action", "video"],
  },
  {
    emoji: "📺",
    name: "television",
    category: "entertainment",
    keywords: ["tv", "watch", "show", "entertainment", "screen"],
  },
  {
    emoji: "📱",
    name: "mobile phone",
    category: "entertainment",
    keywords: ["phone", "mobile", "smartphone", "technology", "app"],
  },
  {
    emoji: "🎪",
    name: "circus tent",
    category: "entertainment",
    keywords: ["circus", "show", "fun", "entertainment", "performance"],
  },

  // Sports & Activities
  {
    emoji: "⚽",
    name: "soccer ball",
    category: "sports",
    keywords: ["football", "soccer", "ball", "sport", "game"],
  },
  {
    emoji: "🏀",
    name: "basketball",
    category: "sports",
    keywords: ["basketball", "ball", "sport", "game", "hoop"],
  },
  {
    emoji: "🏈",
    name: "american football",
    category: "sports",
    keywords: ["football", "american", "ball", "sport", "game"],
  },
  {
    emoji: "⚾",
    name: "baseball",
    category: "sports",
    keywords: ["baseball", "ball", "sport", "game", "bat"],
  },
  {
    emoji: "🎾",
    name: "tennis",
    category: "sports",
    keywords: ["tennis", "ball", "sport", "game", "racket"],
  },
  {
    emoji: "🏐",
    name: "volleyball",
    category: "sports",
    keywords: ["volleyball", "ball", "sport", "game", "net"],
  },
  {
    emoji: "🏓",
    name: "ping pong",
    category: "sports",
    keywords: ["table tennis", "ping pong", "paddle", "ball", "game"],
  },
  {
    emoji: "🏸",
    name: "badminton",
    category: "sports",
    keywords: ["badminton", "racket", "shuttlecock", "sport", "game"],
  },
  {
    emoji: "🥊",
    name: "boxing glove",
    category: "sports",
    keywords: ["boxing", "fight", "glove", "sport", "punch"],
  },
  {
    emoji: "⛳",
    name: "flag in hole",
    category: "sports",
    keywords: ["golf", "hole", "flag", "sport", "course"],
  },
  {
    emoji: "🎿",
    name: "skis",
    category: "sports",
    keywords: ["ski", "snow", "winter", "sport", "mountain"],
  },
  {
    emoji: "🏄‍♂️",
    name: "man surfing",
    category: "sports",
    keywords: ["surf", "wave", "ocean", "sport", "board"],
  },
  {
    emoji: "🏄‍♀️",
    name: "woman surfing",
    category: "sports",
    keywords: ["surf", "wave", "ocean", "sport", "board"],
  },
  {
    emoji: "🧗‍♂️",
    name: "man climbing",
    category: "sports",
    keywords: ["climb", "rock", "mountain", "sport", "adventure"],
  },
  {
    emoji: "🧗‍♀️",
    name: "woman climbing",
    category: "sports",
    keywords: ["climb", "rock", "mountain", "sport", "adventure"],
  },

  // Goals & Achievement
  {
    emoji: "🏆",
    name: "trophy",
    category: "goal",
    keywords: ["win", "award", "champion", "success", "first"],
  },
  {
    emoji: "🥇",
    name: "1st place medal",
    category: "goal",
    keywords: ["gold", "first", "winner", "champion", "best"],
  },
  {
    emoji: "🥈",
    name: "2nd place medal",
    category: "goal",
    keywords: ["silver", "second", "runner-up", "medal", "achievement"],
  },
  {
    emoji: "🥉",
    name: "3rd place medal",
    category: "goal",
    keywords: ["bronze", "third", "medal", "achievement", "podium"],
  },
  {
    emoji: "🎖️",
    name: "military medal",
    category: "goal",
    keywords: ["honor", "achievement", "award", "recognition", "medal"],
  },
  {
    emoji: "⭐",
    name: "star",
    category: "goal",
    keywords: ["favorite", "rating", "excellence", "best", "quality"],
  },
  {
    emoji: "🌟",
    name: "glowing star",
    category: "goal",
    keywords: ["shine", "bright", "special", "achievement", "excellent"],
  },
  {
    emoji: "💎",
    name: "gem stone",
    category: "goal",
    keywords: ["diamond", "valuable", "precious", "rare", "perfect"],
  },
  {
    emoji: "👑",
    name: "crown",
    category: "goal",
    keywords: ["king", "queen", "royalty", "best", "top"],
  },
  {
    emoji: "🔥",
    name: "fire",
    category: "goal",
    keywords: ["hot", "streak", "passionate", "energy", "intense"],
  },
  {
    emoji: "⚡",
    name: "high voltage",
    category: "goal",
    keywords: ["energy", "power", "fast", "electric", "strong"],
  },
  {
    emoji: "🚀",
    name: "rocket",
    category: "goal",
    keywords: ["launch", "fast", "progress", "space", "ambitious"],
  },
  {
    emoji: "💯",
    name: "hundred points",
    category: "goal",
    keywords: ["perfect", "100", "excellent", "complete", "full"],
  },
  {
    emoji: "🎊",
    name: "confetti ball",
    category: "goal",
    keywords: ["celebration", "party", "success", "achievement", "joy"],
  },

  // Nature & Environment
  {
    emoji: "🌱",
    name: "seedling",
    category: "nature",
    keywords: ["grow", "plant", "green", "new", "beginning"],
  },
  {
    emoji: "🌿",
    name: "herb",
    category: "nature",
    keywords: ["plant", "green", "natural", "organic", "fresh"],
  },
  {
    emoji: "🌳",
    name: "deciduous tree",
    category: "nature",
    keywords: ["tree", "nature", "green", "environment", "forest"],
  },
  {
    emoji: "🌲",
    name: "evergreen tree",
    category: "nature",
    keywords: ["pine", "tree", "nature", "green", "forest"],
  },
  {
    emoji: "🌺",
    name: "hibiscus",
    category: "nature",
    keywords: ["flower", "tropical", "colorful", "bloom", "beauty"],
  },
  {
    emoji: "🌸",
    name: "cherry blossom",
    category: "nature",
    keywords: ["flower", "pink", "spring", "bloom", "delicate"],
  },
  {
    emoji: "🌼",
    name: "daisy",
    category: "nature",
    keywords: ["flower", "white", "simple", "pretty", "bloom"],
  },
  {
    emoji: "🌻",
    name: "sunflower",
    category: "nature",
    keywords: ["flower", "yellow", "sun", "bright", "happy"],
  },
  {
    emoji: "🌹",
    name: "rose",
    category: "nature",
    keywords: ["flower", "red", "love", "romantic", "beautiful"],
  },
  {
    emoji: "🌞",
    name: "sun with face",
    category: "nature",
    keywords: ["sunny", "bright", "happy", "warm", "day"],
  },
  {
    emoji: "🌙",
    name: "crescent moon",
    category: "nature",
    keywords: ["night", "sleep", "peaceful", "quiet", "rest"],
  },
  {
    emoji: "☀️",
    name: "sun",
    category: "nature",
    keywords: ["sunny", "bright", "warm", "day", "light"],
  },
  {
    emoji: "🌈",
    name: "rainbow",
    category: "nature",
    keywords: ["colorful", "hope", "beauty", "after rain", "bright"],
  },

  // Emotions & Wellness
  {
    emoji: "😊",
    name: "smiling face with smiling eyes",
    category: "wellness",
    keywords: ["happy", "joy", "positive", "smile", "good"],
  },
  {
    emoji: "😌",
    name: "relieved face",
    category: "wellness",
    keywords: ["calm", "peaceful", "relaxed", "content", "zen"],
  },
  {
    emoji: "🥰",
    name: "smiling face with hearts",
    category: "wellness",
    keywords: ["love", "happy", "affection", "warm", "caring"],
  },
  {
    emoji: "😇",
    name: "smiling face with halo",
    category: "wellness",
    keywords: ["angel", "good", "innocent", "pure", "blessed"],
  },
  {
    emoji: "🤗",
    name: "hugging face",
    category: "wellness",
    keywords: ["hug", "embrace", "comfort", "care", "support"],
  },
  {
    emoji: "🙏",
    name: "folded hands",
    category: "wellness",
    keywords: ["pray", "thanks", "grateful", "hope", "peace"],
  },
  {
    emoji: "💕",
    name: "two hearts",
    category: "wellness",
    keywords: ["love", "care", "affection", "romance", "connection"],
  },
  {
    emoji: "❤️",
    name: "red heart",
    category: "wellness",
    keywords: ["love", "care", "passion", "emotion", "heart"],
  },
  {
    emoji: "🧡",
    name: "orange heart",
    category: "wellness",
    keywords: ["love", "care", "warm", "friendship", "heart"],
  },
  {
    emoji: "💛",
    name: "yellow heart",
    category: "wellness",
    keywords: ["love", "care", "happiness", "joy", "heart"],
  },
  {
    emoji: "💚",
    name: "green heart",
    category: "wellness",
    keywords: ["love", "care", "nature", "growth", "heart"],
  },
  {
    emoji: "💙",
    name: "blue heart",
    category: "wellness",
    keywords: ["love", "care", "calm", "trust", "heart"],
  },
  {
    emoji: "💜",
    name: "purple heart",
    category: "wellness",
    keywords: ["love", "care", "creativity", "magic", "heart"],
  },
  {
    emoji: "🤍",
    name: "white heart",
    category: "wellness",
    keywords: ["love", "care", "pure", "clean", "heart"],
  },

  // Travel & Adventure
  {
    emoji: "✈️",
    name: "airplane",
    category: "travel",
    keywords: ["fly", "travel", "trip", "vacation", "journey"],
  },
  {
    emoji: "🚗",
    name: "automobile",
    category: "travel",
    keywords: ["car", "drive", "road", "trip", "transport"],
  },
  {
    emoji: "🚲",
    name: "bicycle",
    category: "travel",
    keywords: ["bike", "cycle", "ride", "exercise", "green"],
  },
  {
    emoji: "🏔️",
    name: "mountain",
    category: "travel",
    keywords: ["peak", "high", "climb", "adventure", "nature"],
  },
  {
    emoji: "🏖️",
    name: "beach",
    category: "travel",
    keywords: ["sand", "ocean", "vacation", "sun", "relax"],
  },
  {
    emoji: "🏝️",
    name: "desert island",
    category: "travel",
    keywords: ["tropical", "paradise", "vacation", "remote", "peaceful"],
  },
  {
    emoji: "🗺️",
    name: "world map",
    category: "travel",
    keywords: ["map", "explore", "world", "geography", "adventure"],
  },
  {
    emoji: "🧳",
    name: "luggage",
    category: "travel",
    keywords: ["suitcase", "travel", "pack", "trip", "vacation"],
  },
  {
    emoji: "📍",
    name: "round pushpin",
    category: "travel",
    keywords: ["location", "pin", "map", "place", "here"],
  },
  {
    emoji: "🏕️",
    name: "camping",
    category: "travel",
    keywords: ["camp", "tent", "outdoor", "nature", "adventure"],
  },
  {
    emoji: "⛰️",
    name: "mountain",
    category: "travel",
    keywords: ["peak", "climb", "hike", "adventure", "high"],
  },
  {
    emoji: "🌊",
    name: "water wave",
    category: "travel",
    keywords: ["ocean", "sea", "surf", "water", "blue"],
  },
  {
    emoji: "🏞️",
    name: "national park",
    category: "travel",
    keywords: ["nature", "park", "outdoor", "scenery", "peaceful"],
  },
  {
    emoji: "🎒",
    name: "backpack",
    category: "travel",
    keywords: ["bag", "hiking", "school", "travel", "adventure"],
  },

  // Lifestyle & Home
  {
    emoji: "🏠",
    name: "house",
    category: "lifestyle",
    keywords: ["home", "building", "residence", "stay"],
  },
  {
    emoji: "🧹",
    name: "broom",
    category: "lifestyle",
    keywords: ["clean", "sweep", "chore", "tidy"],
  },
  {
    emoji: "🧺",
    name: "basket",
    category: "lifestyle",
    keywords: ["laundry", "storage", "container", "chore"],
  },
  {
    emoji: "🧼",
    name: "soap",
    category: "lifestyle",
    keywords: ["clean", "wash", "hygiene", "bathroom"],
  },
  {
    emoji: "🛁",
    name: "bathtub",
    category: "lifestyle",
    keywords: ["bath", "clean", "relax", "hygiene"],
  },
  {
    emoji: "🚿",
    name: "shower",
    category: "lifestyle",
    keywords: ["clean", "wash", "hygiene", "bathroom"],
  },
  {
    emoji: "🔑",
    name: "key",
    category: "lifestyle",
    keywords: ["lock", "secure", "unlock", "access"],
  },
  {
    emoji: "🐶",
    name: "dog face",
    category: "lifestyle",
    keywords: ["pet", "animal", "friend", "canine"],
  },
  {
    emoji: "🐱",
    name: "cat face",
    category: "lifestyle",
    keywords: ["pet", "animal", "friend", "feline"],
  },
  {
    emoji: "👕",
    name: "t-shirt",
    category: "lifestyle",
    keywords: ["clothing", "fashion", "wear", "casual"],
  },

  // Social
  {
    emoji: "🧑‍🤝‍🧑",
    name: "people holding hands",
    category: "social",
    keywords: ["friends", "couple", "together", "relationship"],
  },
  {
    emoji: "🗣️",
    name: "speaking head",
    category: "social",
    keywords: ["talk", "speak", "communicate", "voice"],
  },
  {
    emoji: "💬",
    name: "speech balloon",
    category: "social",
    keywords: ["chat", "message", "talk", "communication"],
  },
  {
    emoji: "👪",
    name: "family",
    category: "social",
    keywords: ["parents", "children", "together", "love"],
  },

  // Finance
  {
    emoji: "💵",
    name: "dollar banknote",
    category: "finance",
    keywords: ["money", "cash", "currency", "payment"],
  },
  {
    emoji: "🪙",
    name: "coin",
    category: "finance",
    keywords: ["money", "cash", "change", "currency"],
  },
  {
    emoji: "🐷",
    name: "pig face",
    category: "finance",
    keywords: ["piggy bank", "savings", "money", "frugal"],
  },
  {
    emoji: "🏦",
    name: "bank",
    category: "finance",
    keywords: ["money", "savings", "building", "finance"],
  },

  // More Hobbies
  {
    emoji: "🧵",
    name: "thread",
    category: "hobby",
    keywords: ["sew", "craft", "needle", "string"],
  },
  {
    emoji: "🧶",
    name: "yarn",
    category: "hobby",
    keywords: ["knit", "crochet", "craft", "wool"],
  },
  {
    emoji: "🔨",
    name: "hammer",
    category: "hobby",
    keywords: ["build", "tool", "fix", "craft"],
  },
  {
    emoji: "🛠️",
    name: "hammer and wrench",
    category: "hobby",
    keywords: ["tools", "build", "fix", "repair"],
  },
  {
    emoji: "🎤",
    name: "microphone",
    category: "hobby",
    keywords: ["sing", "audio", "record", "music"],
  },
  {
    emoji: "🎧",
    name: "headphone",
    category: "hobby",
    keywords: ["music", "audio", "listen", "sound"],
  },
  {
    emoji: "🎻",
    name: "violin",
    category: "hobby",
    keywords: ["instrument", "music", "classical", "play"],
  },
  {
    emoji: "🧩",
    name: "puzzle piece",
    category: "hobby",
    keywords: ["game", "solve", "challenge", "fit"],
  },

  // More Food
  {
    emoji: "🍞",
    name: "bread",
    category: "food",
    keywords: ["bake", "toast", "sandwich", "grain"],
  },
  {
    emoji: "🥐",
    name: "croissant",
    category: "food",
    keywords: ["pastry", "french", "breakfast", "bake"],
  },
  {
    emoji: "🧀",
    name: "cheese wedge",
    category: "food",
    keywords: ["dairy", "snack", "yellow", "delicious"],
  },
  {
    emoji: "🥩",
    name: "cut of meat",
    category: "food",
    keywords: ["steak", "beef", "protein", "cook"],
  },
  {
    emoji: "🍗",
    name: "poultry leg",
    category: "food",
    keywords: ["chicken", "turkey", "meat", "cook"],
  },
  {
    emoji: "🌮",
    name: "taco",
    category: "food",
    keywords: ["mexican", "eat", "lunch", "dinner"],
  },
  {
    emoji: "🍣",
    name: "sushi",
    category: "food",
    keywords: ["japanese", "fish", "rice", "eat"],
  },
  {
    emoji: "🍜",
    name: "steaming bowl",
    category: "food",
    keywords: ["ramen", "noodles", "soup", "hot"],
  },
  {
    emoji: "🍩",
    name: "doughnut",
    category: "food",
    keywords: ["dessert", "sweet", "treat", "sugar"],
  },
  {
    emoji: "🍪",
    name: "cookie",
    category: "food",
    keywords: ["dessert", "sweet", "treat", "bake"],
  },
  {
    emoji: "🎂",
    name: "birthday cake",
    category: "food",
    keywords: ["dessert", "celebrate", "party", "sweet"],
  },
  {
    emoji: "🍫",
    name: "chocolate bar",
    category: "food",
    keywords: ["dessert", "sweet", "candy", "treat"],
  },
  {
    emoji: "🍿",
    name: "popcorn",
    category: "food",
    keywords: ["movie", "snack", "cinema", "eat"],
  },
  {
    emoji: "🥤",
    name: "cup with straw",
    category: "food",
    keywords: ["drink", "soda", "juice", "beverage"],
  },
] as const;
